name: ci
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: "image tag"
        value: ${{ jobs.build-and-test.outputs.image-tag }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # need this for OIDC
      contents: read
    environment: main
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
